### ISSUE TITLE
Update documentation and logo

### ISSUE THREAD

**Issue by zubairov** [elasticio/sugarcrm-component#17]
- [x]  A logo that is 128x128 (current logo is only 64 x 64).

- [x]  Correct documentation (with screenshots) for all actions and triggers.

**Comment by jhorbulyk** [comment]
There is an interesting problem with the logo where SugarCRM doesn't have an official square logo.  They acknowledge that it is common for people to take a cropping of the cube to use as a square logo.  Should we do that as well or should we display their rectangular logo in square form?

**Comment by zubairov** [comment]
Let’s cut

**Comment by khanzadyan** [comment]
This issue probably needs to be closed. Currently we have a square logo everywhere and the documentation includes images of every trigger/action configuration fields with plenty of descriptions https://docs.elastic.io/components/sugarcrm/
