### ISSUE TITLE
Circle CI build should be updated to V2

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/sugarcrm-component#29]
Currenlty the CircleCI Build does not run as the build config is written against CircleCI V1 which is now deprecated.
![Screenshot from 2019-04-12 14-49-37](https://user-images.githubusercontent.com/5710732/56038427-375b7780-5d32-11e9-8861-96b5444206a3.png)

**Comment by khanzadyan** [comment]
This issue can be closed since the component is using version 2 already.
