### ISSUE TITLE
SugarCRM Url, the app secret and the app ID should be configured in the same place

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/sugarcrm-component#3]
Currently sugar URL and app ID are in the credentials but app secret is in the env variables (and this detail isn’t documented yet).  Ideally these three pieces of instance specific information should be configured in the same place.

**Comment by drobiazko** [comment]
@jhorbulyk can we have our own app ID without having our own sugar instance? I mean we are using the trial.

**Comment by jhorbulyk** [comment]
The app ID must be established per sugarCRM instance.  I can create an app ID for my trial instance but app IDs are not valid across SugarCRM instances.

**Comment by drobiazko** [comment]
So, each of our customers is required to create his own app? Doesn't work as in Salesforce or any other OAuth2 apps where we have our own app id and let people authorize it to access data on their behalf?

**Comment by jhorbulyk** [comment]
If each of our customers has their own sugarCRM instance, then they would be required to create their own app on that instance.

It doesn't work this way in Salesforce or many other services because Salesforce generally has one multi-tenant cloud instance an an app on that cloud instance can be used across tenants on that instance.  It's not clear if there are any sugarCRM versions which support multi-tenancy.

**Comment by jhorbulyk** [comment]
@drobiazko What is the long term expectation on where these three values should be stored?

**Comment by drobiazko** [comment]
@jhorbulyk isn't sugar a cloud service? I'm wondering about your multi-tenancy comment.
