### ISSUE TITLE
`Verify` credentials button does not really verify credentials

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/sugarcrm-component#34]
**Description:** `Verify` credentials button shows that credentials are verified in case of invalid input into credentials input fields.

**STR:**
1. Go to the production stage -> credentials section
2. Find your credentials of your sugarCRM component
3. Input invalid values into input fields
4. Click on `Verify` button
5. See that invalid credentials are 'verified'.

**AR:** Component credentials verification is broken
![image](https://user-images.githubusercontent.com/36419533/65322477-42e78000-dba7-11e9-900e-98ef0472cdea.png)

*Logs:*
```
Starting your Docker container ...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Starting application in apprunner...
Starting slug download ...
Successfully downloaded and extracted slug file
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
No access token found.  Fetching access token with user credentials...
Error: getaddrinfo EBUSY 9238.123123123:443
at errnoException (dns.js:55:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
Exception: Error: getaddrinfo EBUSY 9238.123123123:443
at Object.exports._errnoException (util.js:1014:11)
[INFO  tini (1)] Main child exited normally (with status '0')
```

**ER:** 
1.Invalid credentials are not verified
2. Error message is shown: `Error: Your credentials are not valid. Please see logs for details.`
3. `Verify` button is turned to:
![image](https://user-images.githubusercontent.com/36419533/65322574-8215d100-dba7-11e9-98f6-bf17162828a5.png)

**Comment by andrewreshitko** [comment]
seems the bug is not relevant anymore
![image](https://github.com/elasticio/sugarcrm-component/assets/110159769/1eb287c7-e35f-40dc-a631-be97810abb56)
