### ISSUE TITLE
Investigate account functionality across user password changes

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/sugarcrm-component#4]
Currently, the sugarCRM component stores the users password and then uses that piece of information to fetch a token to do API requests.  In theory, one should be able to use the username/password to fetch a token that can be continuously renewed.  Even if the user then changes their password, the token should remain valid.

**Comment by drobiazko** [comment]
Typically token refresh is done with a `refresh_token`. Do you think Sugar requires password for that?

**Comment by jhorbulyk** [comment]
SugarCRM [does support refresh_token](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.8/Integration/Web_Services/v10/).  If they have implemented this correctly, then one should not require the username/password however, this would have to be verified.

**Comment by drobiazko** [comment]
So what exactly we need to investigate in this issue?

**Comment by jhorbulyk** [comment]
Investigation completed and the component now exclusively relies on refresh tokens to authenticate.
